name: assignment-test
on:
    workflow_dispatch:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run: git submodule update --init --recursive
          - name: Fix root SSH known_hosts
            run: |
              sudo mkdir -p /root/.ssh
              sudo ssh-keygen -f "/root/.ssh/known_hosts" -R github.com || true
              sudo ssh-keyscan github.com | sudo tee -a /root/.ssh/known_hosts
              sudo chmod 600 /root/.ssh/known_hosts
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D